version: '3.9'
services:
  web:
    build: .
    container_name: bloodsociety_web
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=bloodsociety;Username=admin;Password=secret
    depends_on:
      - db
      - kafka
      - emqx
      - redis
    restart: unless-stopped
  db:
    image: postgres:16
    container_name: bloodsociety_db
    environment:
      POSTGRES_DB: bloodsociety
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
  kafka:
    image: bitnami/kafka:latest
    container_name: bloodsociety_kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: unless-stopped
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: bloodsociety_zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped
  emqx:
    image: emqx/emqx:5.6.0
    container_name: bloodsociety_emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    restart: unless-stopped
  redis:
    image: redis:7.2
    container_name: bloodsociety_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  db_data:
  redis_data:
